apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ejemplo1
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/pv-ejemplo1